//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int cnum { get; set; }
        public string cname { get; set; }
        public string city { get; set; }
        public Nullable<int> rating { get; set; }
        public int snum { get; set; }
    }
}
